### ISSUE TITLE
java_version not shown

### ISSUE THREAD

**Issue by jagular-spb** [kvendingoldo/semver-action#1]
https://github.com/kvendingoldo/semver-action/blob/035bb70e332b635d81bf5d96397676b924d00853/main.py#L209

**Comment by kvendingoldo** [comment]
fixed in version 1.10; Pipeline example:
```
name: ci
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      -
        uses: actions/checkout@v3.0.1
        with:
          fetch-depth: 0
      -
        name: Set application version
        id: set_version
        uses: kvendingoldo/semver-action@v1.10
        with:
          primary_branch: main
      -
        name: Generated version
        run: echo ${{ steps.set_version.outputs.version }}
      -
        name: Safe version
        run: echo ${{ steps.set_version.outputs.safe_version }}
      -
        name: Java version
        run: echo ${{ steps.set_version.outputs.java_version }}
```

Output:
![Screen Shot 2022-04-19 at 3 30 38 AM](https://user-images.githubusercontent.com/11614750/163892853-53deb9f4-ec5e-4193-b437-4a0a3ea5d7cd.png)
